---
- name: copy sound warning script
  become: true
  template:
    src: 'templates/akku.sh.j2'
    dest: '/opt/akku.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: copy sound warning video
  become: true
  copy:
    src: "{{ akku_sound_src }}"
    dest: "{{ akku_sound_dest }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: multimedia_akku_warning | bool
