---
- name: Run systemctl daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Run systemctl start battery_check.service
  become: true
  ansible.builtin.systemd:
    name: 'battery_check.service'
    state: started

- name: Run systemctl enable battery_check.timer
  become: true
  ansible.builtin.systemd:
    name: 'battery_check.timer'
    enabled: true
    state: started
